### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by ch1ckenstripper** [Atm4x/tts-with-rvc#1]
I cant get it to work.
Every time I try to use a python program, they are hanging by a thread with the dependencies and coding. I can never get it to do what I want. Why do I need to be a developer to use code that should be already developed? Is that inherent to python projects? I already have CUDA, torch, etc. Everything should just work, but the console window says something about not being able to import from inference.py and jumps off a cliff.
---------------------------------------------------
Use case is for an old videogame with area descriptions and character speech text, but no voiceover. I already found a program that scans an area of the screen and outputs to a text file. I want to use your program because I think RVC is the right tool for quality and speed.
---------------------------------------------------
I'm trying to be able to run the script from a bat file: it should automatically read text thru a RVC model from a text file in a folder.
---------------------------------------------------
Why is this such a typical experience for me, even WITH instructions???
Sorry, and thanks.

**Comment by Atm4x** [comment]
@ch1ckenstripper, Hi, thanks for your issue!

The problem you got is error of installing dependent packages of RVC package (I mean, I can't do anything to fix the other's man package by myself, but I'll try to make a copy and fix it).

So, I will try to fix it soon and then I will let you know!

Could you provide a screenshots of process of the installing the packages?

**Comment by ch1ckenstripper** [comment]
Thanks again, I just hate it when cool things don't work. Here is my install log for the 3 commands in the instructions.
![installoutput](https://github.com/Atm4x/tts-with-rvc/assets/68689899/0155b194-9188-497f-a77a-7db2a9a68976)

I got something like your program jankily working to test, and I ran into an inherent issue with RVC i think. Not sure if this is worth an extra Issue, but it takes about 10-15 seconds from starting my script to hearing output. Could half of this be reduced by keeping the selected RVC model in memory, instead of at command execute? It would be cool to have one command to start inference, and a separate one to load/unload/change models. Would this be possible?
Thank you!

**Comment by Atm4x** [comment]
@ch1ckenstripper I'm on my way to simplifying the usage and installation processes. The original code for RVC, as you said, loads the voice every time the function is executed, and it also loads 'rmvpe'. I'll try to fix that, but there's no guarantee it'll work :/

**Comment by ch1ckenstripper** [comment]
Awesome, thank you for thinking about it.

**Comment by Atm4x** [comment]
@ch1ckenstripper I simplified the usage and changed the architecture of the dependent packages of RVC, so now it is pretty easy to install without problems. As for optimization, I got 2-3 seconds of performance with caching, nothing more. When you run the script, it is loaded into the cache (while the program is running), so to get faster you need to start processing *after* the initial start. I mean, you run the script and *after it processes text for the first time* process all you want. 

So, there is an image with a performance test for my gpu:

![image](https://github.com/Atm4x/tts-with-rvc/assets/96025052/41863cb2-4875-4bc3-9cd4-aa59f59f2211)

**Comment by ch1ckenstripper** [comment]
Wow you really did it! Legendary.
Christopher Lee is going to be narrating nonsense even quicker now! If you think you've gotten it as good as it's going to get, we can close this issue. Thanks again for being interested!
Don't mind me soliciting: If you ever need a digital content maker, check me out @ https://ytjobs.co/talent/profile/178129
