### ISSUE TITLE
filename save

### ISSUE THREAD

**Issue by Anewold1** [Atm4x/tts-with-rvc#4]
i assume im making a error somewhere here however it isnt shown how to use said output_filename. 

i assume its something like this:
path = tts(text=data, pitch=0, output_filename="output.wav")

this however comes back with:
join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by Atm4x** [comment]
@Anewold1 Hi, thanks for the issue! Yes, there was a problem with that. To make your code work now, just reinstall the dependent package:
```
python -m pip install git+https://github.com/Atm4x/rvc-tts-pipeline-fix.git@dev#egg=rvc_tts_pipe --force-reinstall
```

Now it should work

**Comment by Anewold1** [comment]
this works perfectly now, thanks for the patch
