### ISSUE TITLE
install error on ubuntu 22.04

### ISSUE THREAD

**Issue by Anewold1** [Atm4x/tts-with-rvc#5]
after getting it working flawlessly on my windows 11 system i went to push it to use on my linux system, however i ran into the following.

Traceback (most recent call last):
  File "/home/hidden/python/ai/rvc/test.py", line 1, in <module>
    from tts_with_rvc import TTS_RVC
  File "/home/hidden/.local/lib/python3.10/site-packages/tts_with_rvc/__init__.py", line 1, in <module>
    from .inference import *
  File "/home/hidden/.local/lib/python3.10/site-packages/tts_with_rvc/inference.py", line 6, in <module>
    from rvc_tts_pipeline.rvc_infer import rvc_convert
  File "/home/hidden/.local/lib/python3.10/site-packages/rvc_tts_pipeline/rvc_infer.py", line 15, in <module>
    from rvc_lib.vc_infer_pipeline import VC
ModuleNotFoundError: No module named 'rvc_lib'

**Comment by Atm4x** [comment]
@Anewold1 There were some errors while building the rvc and rvclib packages, so they just didn't get installed! I made a patch for it and now it works for me on ubuntu 22.04 subsystem. So now reinstall these two packages:
```
pip install pip==24.0
python -m pip install git+https://github.com/Atm4x/rvc-lib.git@dev#egg=rvc
python -m pip install -e git+https://github.com/Atm4x/rvc-lib.git#egg=rvclib
```
There shouldn't be any dependency conflicts during the installation, but if there are, I recommend you to set up some envs like conda or docker.
Pip with ver 24.0 as some dependent packages cannot be built with newer versions. 

Let me know if there are any other bugs!

**Comment by Anewold1** [comment]
i did have a workaround by just redirecting it to a locally downloaded one, shall try again with this updated method now

**Comment by Anewold1** [comment]
seems to be working
